apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: policy-managed-patch-operator-placement-binding
  namespace: policies
placementRef:
  name: placement-policy-gitops
  apiGroup: apps.open-cluster-management.io
  kind: PlacementRule
subjects:
  - name: policy-managed-patch-operator
    apiGroup: policy.open-cluster-management.io
    kind: Policy