apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-patch-ingresscontroller
  namespace: policies
  annotations:
    policy.open-cluster-management.io/categories: CM Configuration Management, CA Security Assessment and Authorization
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: patch-ingresscontoller
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: redhatcop.redhat.io/v1alpha1
                kind: Patch
                metadata:
                  name: ingresscontoller-patch
                  namespace: patch-operator
                spec:
                  patches:
                    ingress-operator-patch:
                      patchTemplate: |
                        spec:
                          nodePlacement:
                            nodeSelector:
                              matchLabels:
                                node-role.kubernetes.io/infra: ""
                                router: 'true'
                            tolerations:
                            - effect: NoSchedule
                              key: node-role.kubernetes.io/infra
                              value: ''
                      patchType: application/merge-patch+json
                      targetObjectRef:
                        apiVersion: operator.openshift.io/v1
                        kind: IngressController
                        name: default
                        namespace: openshift-ingress-operator
  remediationAction: enforce

