apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-patch-imageregistry
  namespace: policies
  annotations:
    policy.open-cluster-management.io/categories: CM Configuration Management, CA Security Assessment and Authorization
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: patch-imageregistry
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: redhatcop.redhat.io/v1alpha1
                kind: Patch
                kind: PersistentVolumeClaim
                apiVersion: v1
                metadata:
                  name: pvc-image-registry-storage
                  namespace: openshift-image-registry
                spec:
                  accessModes:
                    - ReadWriteMany
                  resources:
                    requests:
                      storage: 100Gi
                  storageClassName: ocs-storagecluster-ceph-rbd
                  volumeMode: Filesystem
            - complianceType: musthave
              objectDefinition:
                apiVersion: redhatcop.redhat.io/v1alpha1
                kind: Patch
                metadata:
                  name: imageregistry-patch
                  namespace: patch-operator
                spec:
                  patches:
                    imageregistry-config-patch:
                      patchTemplate: |
                        spec:
                          managementState: Managed
                          defaultRoute: true
                          storage:
                            managementState: Managed
                            pvc:
                              claim: pvc-image-registry-storage
                          replicas: 3
                      patchType: application/merge-patch+json
                      targetObjectRef:
                        apiVersion: imageregistry.operator.openshift.io/v1
                        kind: Config
                        name: cluster
  remediationAction: enforce

