---
kind: ServiceAccount
apiVersion: v1
metadata:
  namespace: rhacs-operator
  name: argocd
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argocd-edit
  namespace: rhacs-operator
  annotations:
    argocd.argoproj.io/sync-wave: "1"   
subjects:
  - kind: ServiceAccount
    name: argocd
    namespace: rhacs-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit