apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - mappingMethod: claim
    name: SSO-ITS4U-GROUP
    openID:
      claims:
        email:
        - email
        name:
        - name
        preferredUsername:
        - preferred_username
      clientID: ocp-lab2.its4u.eu
      clientSecret:
        name: openid-client-secret-tltvc
      extraScopes: []
      issuer: https://sso.its4u-group.com/auth/realms/ITs4U
    type: OpenID
  templates:
    error:
      name: error-template
    login:
      name: login-template
    providerSelection:
      name: providers-template