apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
    - mappingMethod: claim
      name: SSO-OCP
      openID:
        claims:
          email:
            - email
          name:
            - name
          preferredUsername:
            - preferred_username
        clientID: OpenshiftClientID
        clientSecret:
          name: openid-client-secret-its4u
        extraScopes: []
        issuer: 'https://sso.its4u-group.com/auth/realms/ocp-lab'
      type: OpenID
  templates:

