apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: infra-placement-policy
  namespace: policies
spec:
  clusterConditions:
    - status: 'True'
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: infra-nodes
        operator: In
        values:
          - present