apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: policy-managed-acs-secured-cluster-placement-binding
  namespace: policies
placementRef:
  name: placement-policy-acs-central-cluster
  apiGroup: apps.open-cluster-management.io
  kind: PlacementRule
subjects:
  - name: policy-managed-acs-central-cluster
    apiGroup: policy.open-cluster-management.io
    kind: Policy
