apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: policy-managed-openshift-gitops-operator-placement-binding
  namespace: policies
placementRef:
  name: placement-policy-all-envs
  apiGroup: apps.open-cluster-management.io
  kind: PlacementRule
subjects:
  - name: policy-managed-gitops-operator
    apiGroup: policy.open-cluster-management.io
    kind: Policy