apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: policy-managed-patch-registry-placement-binding
  namespace: policies
placementRef:
  name: infra-placement-policy
  apiGroup: apps.open-cluster-management.io
  kind: PlacementRule
subjects:
  - name: patch-imageregistry-move-to-infra
    apiGroup: policy.open-cluster-management.io
    kind: Policy