apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: policy-managed-web-terminal-operator-placement-binding
  namespace: policies
placementRef:
  name: placement-policy-web-terminal
  apiGroup: apps.open-cluster-management.io
  kind: PlacementRule
subjects:
  - name: policy-managed-terminal-operator
    apiGroup: policy.open-cluster-management.io
    kind: Policy